clearTranscription = ->
  tt = new Transcription
  $('#round_trans_area').val ''
  return

startListening = ->
  cl 'startListening'
  dictate.startListening()
  return

stopListening = ->
  dictate.stopListening()
  return

custom_cancel = ->
  dictate.cancel()
  return


# ---
# generated by js2coffee 2.2.0
FlowRouter.route '/voiceEmr', action: ->
  BlazeLayout.render 'main',
    content: 'voiceEmr'
    hasHeader: true
    hasFooter: true
  return

Template.voiceEmr.onCreated ->
  inst = @
  inst.subscribe 'pub_voiceEMRs', mDefine.cstInfo.get()?._id
  datacontext = inst.data
  datacontext.selData = new ReactiveVar()
  datacontext.curData = new ReactiveVar({})
  datacontext.isRecording = new ReactiveVar()
  datacontext.isRecording.set false

clickedFlag = false
Template.voiceEmr.onRendered ->
  # init()  #STT init
  # window.parent.postMessage 'stt_init', '*'

  # addEvent = (element, eventName, callback) ->
  #   if element.addEventListener
  #     element.addEventListener eventName, callback, false
  #   return

  # addEvent document, 'keypress', (e) ->
  #   e = e or window.event
  #   # use e.keyCode
  #   if e.keyCode is 43
  #     $("[name=insert_mic]").click()
  #     str = $('#round_trans_area').val().replace(/\+/gi, '')
  #     $('#round_trans_area').val(str)
  #   return

  # messagesHandler = (evt) ->
  #   cl 'message is comming from parent'
  #   #{type: "stt_text", value: "음성변환text"}
  #   #{type: "stt_command", value: "음성변환text"}
  #   if evt.data?.type is "stt_text"
  #     console.log(evt.data.value)
  #     $('#round_trans_area').val evt.data.value

  # addEvent window, 'message', messagesHandler, false

Template.voiceEmr.helpers
  cstInfo: -> if (info=mDefine.cstInfo.get())? then return info
  emrs: -> CollectionVoiceEMRs.find({}, {sort: yymmdd: 1})
  selData: -> Template.instance().data?.selData.get()
  curData: -> Template.instance().data?.curData.get()
  isRecording: -> Template.instance().data?.isRecording.get()

Template.voiceEmr.events
  'click [name=btnPastEMR]': (evt, inst) ->
    _id = $(evt.target).attr('data-id')
    datacontext = inst.data
    datacontext.selData.set CollectionVoiceEMRs.findOne(_id: _id)
    $('#popup').css('display', 'block')
    $('#emr_pop_1').css('display', 'block')
  'click [name=btnClosePastPopup]': (evt, inst) ->
    $('#popup').css('display', 'none')
    $('.pop03').css('display', 'none')
  'click [name=btnGetPastPopup]': (evt, inst) ->
    $('#popup').css('display', 'none')
    $('.pop03').css('display', 'none')
    datacontext = inst.data
    datacontext.curData.set datacontext.selData.get()
    datacontext.selData.set({})
  'click [name=btnInsertPopup]': (evt, inst) ->
    $('#popup').css('display', 'block')
    $('#emr_pop_2').css('display', 'block')
  'click [name=btnSaveCurData]': (evt, inst) ->
    $('.pop03').css('display', 'none')
    $('#dim').css('display', 'block')
  'click [name=goToCstList]': ->
    FlowRouter.go '/patientList'
  'click [name=goToNextCst]': (evt, inst) ->
    Meteor.call 'moveToNextCst', mDefine.cstInfo.get()._id, (err, rslt) ->
      if err then alert err
      else
        cl rslt
        mDefine.cstInfo.set rslt
        FlowRouter.go '/moveToBed'

  'click [name=insert_write]': (evt, inst) ->
    field = $('[name=pop_emr]:checked').attr('id')
    unless field?.length > 0 then return alert("입력항목을 선택해주세요.")
    clickedFlag = false
    $('[name=insert_textarea]').focus()
    # stopListening();
    mUtils.fr_keyOn();
  'click [name=insert_mic]': (evt, inst) ->
    #버튼은 비활성화, 마이크 버튼 누르면 변경
#    cl clickedFlag
    field = $('[name=pop_emr]:checked').attr('id')
    value = $('[name=insert_textarea]').val()
    unless field?.length > 0 then return alert("입력항목을 선택해주세요.")
    datacontext = inst.data

    if clickedFlag
      clickedFlag = false
      $('[name=insert_textarea]').focus()
#      custom_cancel();
      datacontext.isRecording.set false
      window.parent.postMessage 'stt_stop', '*'
      #음성정지때 현재 내용 저장(저장버튼으로 나가지 않아도 되게)
      cl curData = datacontext.curData.get()
      cl curData[field] = value
      cl curData = datacontext.curData.get()
      datacontext.curData.set curData
    else
      x = document.getElementById("myAudio")
      x.play()
      clickedFlag = true
#      startListening();
      datacontext.isRecording.set true
      window.parent.postMessage 'stt_start', '*'

  'click [name=insert_save]': (evt, inst) ->
    clickedFlag = false
    $('[name=insert_textarea]').focus()
    field = $('[name=pop_emr]:checked').attr('id')
    value = $('[name=insert_textarea]').val()
    unless field?.length > 0 then return alert("입력항목을 선택해주세요.")
#    custom_cancel();
#    stopListening();
#    clearTranscription();  #음성저장내용삭
    #stop을 안하고 저장하는 케이스가 있어 저장 누를시 stop 과정 추가 테스트 필요
    datacontext = inst.data
    datacontext.isRecording.set false
#    window.parent.postMessage 'stt_stop', '*'

    window.parent.postMessage 'stt_save', '*'
    datacontext = inst.data
    curData = datacontext.curData.get()
    curData[field] = value
    datacontext.curData.set curData
    $('#popup').css('display', 'none')
    $('.pop03').css('display', 'none')
    mUtils.fr_keyOff();
  'click [name=pop_emr]': (evt, inst) ->
    field = $('[name=pop_emr]:checked').attr('id')
    value = $('[name=insert_textarea]').val()
    datacontext = inst.data
    curData = datacontext.curData.get()
#    cl curData[field]
    $('[name=insert_textarea]').val(curData[field])

  'click [name=btn_del]': (evt, inst) ->
    evt.preventDefault()
    datacontext = inst.data
#    if datacontext.isRecording.get()
    $('[name=insert_textarea]').val('')
